# Generated by Django 5.1.2 on 2025-02-22 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_accounttype_transactiontype_phonenumber_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="provinces",
            new_name="province",
        ),
    ]
