# Generated by Django 5.1.2 on 2025-02-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_rename_provinces_user_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_balance",
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="transactiontype",
            name="name",
            field=models.CharField(
                choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.DeleteModel(
            name="PhoneNumber",
        ),
    ]
